### ISSUE TITLE
Update finalproject

### ISSUE THREAD

**Issue by ghost** [jhbforlife/hackbright#26]
_- ~Add favorites feature~_
_- ~Add README.md~_

**Comment by ghost** [comment]
- Favorites
  - When a favorited item is removed on the Favorites screen, re-render the favorites screen instead of the next time screen navigation takes place
  - When a user is searching for a recipe and selects a previously favorited recipe, use the saved info instead of fetching from the API (like is currently done in Favorites). May need to do this for Main as well.
- Web
  - Currently functional, but styling needs to be fixed.

**Comment by jhbforlife** [comment]
When a user is searching for a recipe and selects a previously favorited recipe, use the saved info instead of fetching from the API (like is currently done in Favorites). May need to do this for Main as well.

Implemented [6786570](https://github.com/jhbforlife/hackbright/commit/67865705fce7fd3ab714d9b9423b2deb3c3fd141)

**Comment by jhbforlife** [comment]
When a favorited item is removed on the Favorites screen, re-render the favorites screen instead of the next time screen navigation takes place

Implemented [e50cdcb](https://github.com/jhbforlife/hackbright/commit/e50cdcbce19c396aede0c599a112bce960a3135b)

**Comment by jhbforlife** [comment]
Currently functional, but styling needs to be fixed.

Current Favorites implementation does not support web, not going to work on styling. Opening PR
